<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Jellyfin.Plugin.QBittorrent</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\PluginConfiguration.html" />
    <EmbeddedResource Include="Resources\PluginConfiguration.html" />
    <None Remove="Web\index.html" />
    <EmbeddedResource Include="Web\index.html" />
  </ItemGroup>

</Project>
